### PR TITLE
Edit voucher copy and default selection

### LINKED ISSUE #543: Default "Do you have a voucher?" question to Yes
This should apply in both the backend and frontend code.

### PR DESCRIPTION
**Pull request by rachelekm**
## Overview

This PR updates the default "Do you have a voucher?" field to “yes” on the frontend (`True` in admin) as well as updates any user-facing copy that includes “voucher” to specify “Boston Housing Authority voucher” instead. 

### Checklist

- [x] Run `./scripts/format` to lint, format, and fix the application source code.

### Notes

- I decided to leave any translations that include "voucher" alone. I _could_ pop in the "BHA" label but I think I better keep my hands off until someone can formally translate.
- There's some copy that reference "Client ID" that I think was used for the search page, but is no longer used elsewhere in the app (`Accounts.InvalidVoucherNumber`, `Accounts.MissingVoucherNumber`, `Accounts.Voucher`). I switched it to "Boston Housing Authority voucher" to it's consistent but maybe worth just deleting these lines altogether?

## Testing Instructions

 * `scripts/update`
 * `scripts/server`
 * Navigate to [frontend site](http://localhost:9966/) and create a new user. Confirm "Do you have a voucher?" field defaults to “yes”.
 * Work way through the site to confirm any copy that included "voucher" now specifies "Boston Housing Authority voucher". From what I can find this is mostly limited to the edit profile page for new and verified users. 
 * Navigate to [admin](http://localhost:9966/) and create a new `UserProfile`. Confirm the "Has a Boston Housing Authority voucher" field defaults to "checked".
 * Confirm any other fields on the admin that include "voucher" are now "Boston Housing Authority voucher".

Resolves #543 #544

### CODE REVIEW

**Review by ktohalloran — APPROVED** [review]
This looks good! I think you're right that just trying to add "BHA" into the previously translated text is probably not very helpful; however, I think leaving the translations as is will make them difficult to find again for translation. So I think somehow marking those&#8212;whether by replacing them with their English counterparts for now or adding a comment by each that links to #532 or adding a list of them to the issue itself&#8212;just something that makes it obvious they're going to need new translations when we get to that step. 

As for the strings in the translation files that are no longer used--@ddohler would it be worth adding clean up of those files, removing strings that are not in use within the app anymore, to issue #532?

**Comment by ddohler** [comment]
@ktohalloran Good call about translatios -- I think adding a list to #532 is the right way to go. I would probably skip cleaning up the unused translations given the budget; they're messy but harmless. We should make an issue to clean them up later though.

**Comment by ktohalloran** [comment]
Sounds good, I can make that issue now while I'm thinking about it.

**Comment by rachelekm** [comment]
Thanks, all! @ktohalloran thanks for making those issues and good point about recording the missed translations for later. For #532, Here's a table outlining which phrases related to this PR have updated copy but aren't translated and others that are translated but have outdated copy and need to be re-translated: 
|  | ES | ES | ZH | ZH |
| --- | --- | --- | --- | --- |
||Translated|Updated| Translated|Updated|
| SignIn.Greeting | X | | X | |
| Profile.CreateClientAccountExistsError | X | | | X |
| Profile.HasVoucher |  | X | | X |
| Profile.VoucherNumber |  | X | | X |
| Profile.VoucherRooms | X | | X | |

And then the ones I found related to this PR that will need to be dropped for #548 are:
Accounts.InvalidVoucherNumber
Accounts.MissingVoucherNumber
Accounts.Voucher
Profile.ChooseVoucher

**Pull request merged**
